#goal definition
sensor_msgs/PointCloud2 scancloud
sensor_msgs/PointCloud2 pointmap
geometry_msgs/Point valid_rotation_axis
---
#result definition
geometry_msgs/PoseStamped estimated_pose
---
#feedback
float32 aligned_percentage
float32 normalized_error
