distance_threshold: 0.03
evaluation_threshold: 0.02
min_overlapping_percentage: 0.3
number_subclouds: 5
icp_eps: 1.0e-05
icp_eps2: 1.0e-03
max_icp_it: 300
max_numerical_error: 1.0e-04
max_percentage: 0.85

size_source: 300
size_target: 4000
max_icp_evaluations: 4000
max_depth: 2
lambda: 1
mu: 1
number_rotation_samples = 8;
